Update ui-stages-build-template-angular-dotnet.yml

diff --git a/.github/workflows/ui-stages-build-template-angular-dotnet.yml b/.github/workflows/ui-stages-build-template-angular-dotnet.yml
--- a/.github/workflows/ui-stages-build-template-angular-dotnet.yml
+++ b/.github/workflows/ui-stages-build-template-angular-dotnet.yml
@@ -92,9 +92,9 @@ jobs:
       with:
         dotnet-version: '9.x.x'
 
-    - name: Remove existing NuGet source
-      run: |
-        dotnet nuget remove source EcoviumCommon || echo "Source not found, skipping removal"
+    # - name: Remove existing NuGet source
+    #   run: |
+    #     dotnet nuget remove source EcoviumCommon || echo "Source not found, skipping removal"
 
     - name: List Nuget Sources
       run: dotnet nuget list source
@@ -104,6 +104,11 @@ jobs:
       env:
         NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
+    - name: Dotnet Build
+      run: dotnet build ${{ env.projectCsprojPath }} --configuration ${{ env.buildConfiguration }} -o app/build
+      env:
+        NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+        
 #   build:
 #     name: Build
 #     runs-on: ubuntu-latest
