Update ui-stages-build-template-angular-dotnet.yml

diff --git a/.github/workflows/ui-stages-build-template-angular-dotnet.yml b/.github/workflows/ui-stages-build-template-angular-dotnet.yml
--- a/.github/workflows/ui-stages-build-template-angular-dotnet.yml
+++ b/.github/workflows/ui-stages-build-template-angular-dotnet.yml
@@ -93,39 +93,39 @@ jobs:
       with:
         persist-credentials: true
 
-    - uses: actions/setup-dotnet@v4
-      with:
-        dotnet-version: '8.x.x'
+    # - uses: actions/setup-dotnet@v4
+    #   with:
+    #     dotnet-version: '8.x.x'
 
-    - name: Remove existing NuGet source
-      run: |
-        dotnet nuget remove source EcoviumCommon || echo "Source not found, skipping removal"
+    # - name: Remove existing NuGet source
+    #   run: |
+    #     dotnet nuget remove source EcoviumCommon || echo "Source not found, skipping removal"
 
-    - name: Dotnet restore
-      run: dotnet restore ${{ inputs.projectCsprojPath }}
-      env:
-        NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+    # - name: Dotnet restore
+    #   run: dotnet restore ${{ inputs.projectCsprojPath }}
+    #   env:
+    #     NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
-    - name: List Nuget Sources
-      run: dotnet nuget list source
+    # - name: List Nuget Sources
+    #   run: dotnet nuget list source
 
-    - name: Dotnet Build
-      run: dotnet build ${{ inputs.projectCsprojPath }} --configuration ${{ env.buildConfiguration }} -o app/build
-      env:
-        NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+    # - name: Dotnet Build
+    #   run: dotnet build ${{ inputs.projectCsprojPath }} --configuration ${{ env.buildConfiguration }} -o app/build
+    #   env:
+    #     NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
-    - name: Dotnet Publish
-      if: always()
-      run: |
-        dotnet publish \
-        --configuration ${{ env.buildConfiguration }} \
-        -o ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker/app/publish/
+    # - name: Dotnet Publish
+    #   if: always()
+    #   run: |
+    #     dotnet publish \
+    #     --configuration ${{ env.buildConfiguration }} \
+    #     -o ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker/app/publish/
 
-    - name: List files in app/publish
-      if: always()
-      run: |
-        ls -R ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker/app/publish/
-      shell: pwsh
+    # - name: List files in app/publish
+    #   if: always()
+    #   run: |
+    #     ls -R ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker/app/publish/
+    #   shell: pwsh
 
     - name: Login to ACR
       uses: docker/login-action@v3
@@ -134,14 +134,14 @@ jobs:
         username: "$ACR_USER_NAME"
         password: "$ACR_PASSWORD"
 
-    - name: Docker build and push
-      if: always()
-      run: |
-        export TAG=$(echo "${TAG_NAME}" | tr '/' '_')
-        export SERVICE=$(echo "${SERVICE_NAME}")
+    # - name: Docker build and push
+    #   if: always()
+    #   run: |
+    #     export TAG=$(echo "${TAG_NAME}" | tr '/' '_')
+    #     export SERVICE=$(echo "${SERVICE_NAME}")
 
-        docker login "$ACR_NAME" --username "$ACR_USER_NAME" --password "$ACR_PASSWORD"
-        docker build . -t container/"$SERVICE":"$TAG"
-        docker tag container/"$SERVICE":"$TAG" acrsimplechaindev.azurecr.io/container/"$SERVICE":"$TAG"
-        docker push acrsimplechaindev.azurecr.io/container/"$SERVICE":"$TAG"
-      working-directory: ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker
+    #     docker login "$ACR_NAME" --username "$ACR_USER_NAME" --password "$ACR_PASSWORD"
+    #     docker build . -t container/"$SERVICE":"$TAG"
+    #     docker tag container/"$SERVICE":"$TAG" acrsimplechaindev.azurecr.io/container/"$SERVICE":"$TAG"
+    #     docker push acrsimplechaindev.azurecr.io/container/"$SERVICE":"$TAG"
+    #   working-directory: ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker
