Update ui-stages-build-template-angular-dotnet.yml

diff --git a/.github/workflows/ui-stages-build-template-angular-dotnet.yml b/.github/workflows/ui-stages-build-template-angular-dotnet.yml
--- a/.github/workflows/ui-stages-build-template-angular-dotnet.yml
+++ b/.github/workflows/ui-stages-build-template-angular-dotnet.yml
@@ -99,39 +99,39 @@ jobs:
       with:
         persist-credentials: true
 
-    - uses: actions/setup-dotnet@v4
-      with:
-        dotnet-version: '8.x.x'
+    # - uses: actions/setup-dotnet@v4
+    #   with:
+    #     dotnet-version: '8.x.x'
 
-    - name: Remove existing NuGet source
-      run: |
-        dotnet nuget remove source EcoviumCommon || echo "Source not found, skipping removal"
+    # - name: Remove existing NuGet source
+    #   run: |
+    #     dotnet nuget remove source EcoviumCommon || echo "Source not found, skipping removal"
 
-    - name: Dotnet restore
-      run: dotnet restore ${{ inputs.projectCsprojPath }}
-      env:
-        NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+    # - name: Dotnet restore
+    #   run: dotnet restore ${{ inputs.projectCsprojPath }}
+    #   env:
+    #     NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
-    - name: List Nuget Sources
-      run: dotnet nuget list source
+    # - name: List Nuget Sources
+    #   run: dotnet nuget list source
 
-    - name: Dotnet Build
-      run: dotnet build ${{ inputs.projectCsprojPath }} --configuration ${{ env.buildConfiguration }} -o app/build
-      env:
-        NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+    # - name: Dotnet Build
+    #   run: dotnet build ${{ inputs.projectCsprojPath }} --configuration ${{ env.buildConfiguration }} -o app/build
+    #   env:
+    #     NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
-    - name: Dotnet Publish
-      if: always()
-      run: |
-        dotnet publish \
-        --configuration ${{ env.buildConfiguration }} \
-        -o ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker/app/publish/
+    # - name: Dotnet Publish
+    #   if: always()
+    #   run: |
+    #     dotnet publish \
+    #     --configuration ${{ env.buildConfiguration }} \
+    #     -o ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker/app/publish/
 
-    - name: List files in app/publish
-      if: always()
-      run: |
-        ls -R ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker/app/publish/
-      shell: pwsh
+    # - name: List files in app/publish
+    #   if: always()
+    #   run: |
+    #     ls -R ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker/app/publish/
+    #   shell: pwsh
 
     # - name: Login to ACR
     #   uses: docker/login-action@v3
