Update ui-stages-build-template-angular-dotnet.yml

diff --git a/.github/workflows/ui-stages-build-template-angular-dotnet.yml b/.github/workflows/ui-stages-build-template-angular-dotnet.yml
--- a/.github/workflows/ui-stages-build-template-angular-dotnet.yml
+++ b/.github/workflows/ui-stages-build-template-angular-dotnet.yml
@@ -93,55 +93,56 @@ jobs:
       with:
         persist-credentials: true
 
-    # - uses: actions/setup-dotnet@v4
-    #   with:
-    #     dotnet-version: '8.x.x'
-
-    # - name: Remove existing NuGet source
-    #   run: |
-    #     dotnet nuget remove source EcoviumCommon || echo "Source not found, skipping removal"
-
-    # - name: Dotnet restore
-    #   run: dotnet restore ${{ inputs.projectCsprojPath }}
-    #   env:
-    #     NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-
-    # - name: List Nuget Sources
-    #   run: dotnet nuget list source
-
-    # - name: Dotnet Build
-    #   run: dotnet build ${{ inputs.projectCsprojPath }} --configuration ${{ env.buildConfiguration }} -o app/build
-    #   env:
-    #     NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-
-    # - name: Dotnet Publish
-    #   if: always()
-    #   run: |
-    #     dotnet publish \
-    #     --configuration ${{ env.buildConfiguration }} \
-    #     -o ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker/app/publish/
-
-    # - name: List files in app/publish
-    #   if: always()
-    #   run: |
-    #     ls -R ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker/app/publish/
-    #   shell: pwsh
-
-    - name: Login to ACR
-      uses: docker/login-action@v3
+    - uses: actions/setup-dotnet@v4
       with:
-        registry: acrsimplechaindev.azurecr.io
-        username: "$ACR_USER_NAME"
-        password: "$ACR_PASSWORD"
+        dotnet-version: '8.x.x'
 
-    # - name: Docker build and push
-    #   if: always()
-    #   run: |
-    #     export TAG=$(echo "${TAG_NAME}" | tr '/' '_')
-    #     export SERVICE=$(echo "${SERVICE_NAME}")
+    - name: Remove existing NuGet source
+      run: |
+        dotnet nuget remove source EcoviumCommon || echo "Source not found, skipping removal"
 
-    #     docker login "$ACR_NAME" --username "$ACR_USER_NAME" --password "$ACR_PASSWORD"
-    #     docker build . -t container/"$SERVICE":"$TAG"
-    #     docker tag container/"$SERVICE":"$TAG" acrsimplechaindev.azurecr.io/container/"$SERVICE":"$TAG"
-    #     docker push acrsimplechaindev.azurecr.io/container/"$SERVICE":"$TAG"
-    #   working-directory: ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker
+    - name: Dotnet restore
+      run: dotnet restore ${{ inputs.projectCsprojPath }}
+      env:
+        NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+
+    - name: List Nuget Sources
+      run: dotnet nuget list source
+
+    - name: Dotnet Build
+      run: dotnet build ${{ inputs.projectCsprojPath }} --configuration ${{ env.buildConfiguration }} -o app/build
+      env:
+        NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+
+    - name: Dotnet Publish
+      if: always()
+      run: |
+        dotnet publish \
+        --configuration ${{ env.buildConfiguration }} \
+        -o ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker/app/publish/
+
+    - name: List files in app/publish
+      if: always()
+      run: |
+        ls -R ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker/app/publish/
+      shell: pwsh
+
+    # - name: Login to ACR
+    #   uses: docker/login-action@v3
+    #   with:
+    #     registry: acrsimplechaindev.azurecr.io
+    #     username: "$ACR_USER_NAME"
+    #     password: "$ACR_PASSWORD"
+
+    - name: Docker build and push
+      if: always()
+      run: |
+        export TAG=$(echo "${TAG_NAME}" | tr '/' '_')
+        export SERVICE=$(echo "${SERVICE_NAME}")
+
+        az account set --subscription 7ae7d6f7-74b7-4165-a38e-6cfc79f940b0
+        docker login "$ACR_NAME" --username "$ACR_USER_NAME" --password "$ACR_PASSWORD"
+        docker build . -t container/"$SERVICE":"$TAG"
+        docker tag container/"$SERVICE":"$TAG" acrsimplechaindev.azurecr.io/container/"$SERVICE":"$TAG"
+        docker push acrsimplechaindev.azurecr.io/container/"$SERVICE":"$TAG"
+      working-directory: ${{ github.workspace }}/devops/ui/${{ inputs.serviceName }}/docker
