Update ui-stages-build-template-angular-dotnet.yml

diff --git a/.github/workflows/ui-stages-build-template-angular-dotnet.yml b/.github/workflows/ui-stages-build-template-angular-dotnet.yml
--- a/.github/workflows/ui-stages-build-template-angular-dotnet.yml
+++ b/.github/workflows/ui-stages-build-template-angular-dotnet.yml
@@ -92,28 +92,17 @@ jobs:
       with:
         dotnet-version: '9.x.x'
 
-    - name: Remove existing NuGet source
-      run: |
-        dotnet nuget remove source EcoviumCommon || echo "Source not found, skipping removal"
-
-    # - name: Authenticate to Azure DevOps NuGet feed
+    # - name: Remove existing NuGet source
     #   run: |
-    #     dotnet nuget add source https://pkgs.dev.azure.com/ecovium-cloud-platform/_packaging/EcoviumCommon/nuget/v3/index.json \
-    #       --name EcoviumCommon \
-    #       --username az \
-    #       --password ${{ secrets.NUGET_AUTH_TOKEN }} \
-    #       --store-password-in-clear-text
+    #     dotnet nuget remove source EcoviumCommon || echo "Source not found, skipping removal"
 
-    - name: List Nuget Sources Before
+    - name: List Nuget Sources
       run: dotnet nuget list source
 
     - name: Dotnet restore
-      run: dotnet restore ${{ inputs.projectCsprojPath }} --configfile nuget.config
+      run: dotnet restore ${{ inputs.projectCsprojPath }}
       env:
         NUGET_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-
-    - name: List Nuget Sources After
-      run: dotnet nuget list source
 
 #   build:
 #     name: Build
